<?php

namespace Container6h5wGzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BHJINJ4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bHJINJ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bHJINJ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::admin' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController::adminAddVideoGame' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController::adminRemoveVideoGame' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController::videogamesCard' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController::videogamesList' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController::calculateAge' => ['privates', '.service_locator.bTJtRsn', 'get_ServiceLocator_BTJtRsnService', true],
            'App\\Controller\\SecurityController::isMinimumAgeMet' => ['privates', '.service_locator.bTJtRsn', 'get_ServiceLocator_BTJtRsnService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController::publicProfile' => ['privates', '.service_locator.PJTxOAX', 'get_ServiceLocator_PJTxOAXService', true],
            'App\\Controller\\UserController::updateProfileFields' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VideoGameController::delete' => ['privates', '.service_locator..b29EWt', 'get_ServiceLocator__B29EWtService', true],
            'App\\Controller\\VideoGameController::edit' => ['privates', '.service_locator..b29EWt', 'get_ServiceLocator__B29EWtService', true],
            'App\\Controller\\VideoGameController::index' => ['privates', '.service_locator.jpr6vfM', 'get_ServiceLocator_Jpr6vfMService', true],
            'App\\Controller\\VideoGameController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VideoGameController::show' => ['privates', '.service_locator.J8C_T7p', 'get_ServiceLocator_J8CT7pService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:admin' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController:adminAddVideoGame' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AdminController:adminRemoveVideoGame' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController:videogamesCard' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DefaultController:videogamesList' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController:calculateAge' => ['privates', '.service_locator.bTJtRsn', 'get_ServiceLocator_BTJtRsnService', true],
            'App\\Controller\\SecurityController:isMinimumAgeMet' => ['privates', '.service_locator.bTJtRsn', 'get_ServiceLocator_BTJtRsnService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController:publicProfile' => ['privates', '.service_locator.PJTxOAX', 'get_ServiceLocator_PJTxOAXService', true],
            'App\\Controller\\UserController:updateProfileFields' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\VideoGameController:delete' => ['privates', '.service_locator..b29EWt', 'get_ServiceLocator__B29EWtService', true],
            'App\\Controller\\VideoGameController:edit' => ['privates', '.service_locator..b29EWt', 'get_ServiceLocator__B29EWtService', true],
            'App\\Controller\\VideoGameController:index' => ['privates', '.service_locator.jpr6vfM', 'get_ServiceLocator_Jpr6vfMService', true],
            'App\\Controller\\VideoGameController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VideoGameController:show' => ['privates', '.service_locator.J8C_T7p', 'get_ServiceLocator_J8CT7pService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::admin' => '?',
            'App\\Controller\\AdminController::adminAddVideoGame' => '?',
            'App\\Controller\\AdminController::adminRemoveVideoGame' => '?',
            'App\\Controller\\DefaultController::index' => '?',
            'App\\Controller\\DefaultController::videogamesCard' => '?',
            'App\\Controller\\DefaultController::videogamesList' => '?',
            'App\\Controller\\SecurityController::calculateAge' => '?',
            'App\\Controller\\SecurityController::isMinimumAgeMet' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\UserController::publicProfile' => '?',
            'App\\Controller\\UserController::updateProfileFields' => '?',
            'App\\Controller\\VideoGameController::delete' => '?',
            'App\\Controller\\VideoGameController::edit' => '?',
            'App\\Controller\\VideoGameController::index' => '?',
            'App\\Controller\\VideoGameController::new' => '?',
            'App\\Controller\\VideoGameController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:admin' => '?',
            'App\\Controller\\AdminController:adminAddVideoGame' => '?',
            'App\\Controller\\AdminController:adminRemoveVideoGame' => '?',
            'App\\Controller\\DefaultController:index' => '?',
            'App\\Controller\\DefaultController:videogamesCard' => '?',
            'App\\Controller\\DefaultController:videogamesList' => '?',
            'App\\Controller\\SecurityController:calculateAge' => '?',
            'App\\Controller\\SecurityController:isMinimumAgeMet' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\UserController:publicProfile' => '?',
            'App\\Controller\\UserController:updateProfileFields' => '?',
            'App\\Controller\\VideoGameController:delete' => '?',
            'App\\Controller\\VideoGameController:edit' => '?',
            'App\\Controller\\VideoGameController:index' => '?',
            'App\\Controller\\VideoGameController:new' => '?',
            'App\\Controller\\VideoGameController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
