<?php

namespace Container6h5wGzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__B29EWtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..b29EWt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..b29EWt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'videoGame' => ['privates', '.errored..service_locator..b29EWt.App\\Entity\\VideoGame', NULL, 'Cannot autowire service ".service_locator..b29EWt": it needs an instance of "App\\Entity\\VideoGame" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'videoGame' => 'App\\Entity\\VideoGame',
        ]);
    }
}
