<?php

namespace ContainerZK7Z6LU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..b29EWt.App\Entity\VideoGame' shared service.
     *
     * @return \App\Entity\VideoGame
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..b29EWt": it needs an instance of "App\\Entity\\VideoGame" but this type has been excluded in "config/services.yaml".');
    }
}
