<?php

namespace ContainerOuEtSow;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_BTJtRsn_DateTimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bTJtRsn.DateTime' shared service.
     *
     * @return \DateTime
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bTJtRsn": it references class "DateTime" but no such service exists.');
    }
}
