<?php

namespace ContainerOuEtSow;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BTJtRsnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bTJtRsn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bTJtRsn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'birthday' => ['privates', '.errored..service_locator.bTJtRsn.DateTime', NULL, 'Cannot autowire service ".service_locator.bTJtRsn": it references class "DateTime" but no such service exists.'],
        ], [
            'birthday' => 'DateTime',
        ]);
    }
}
