<?php

namespace ContainerVSQ3N15;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGame2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J8C_T7p.App\Entity\VideoGame' shared service.
     *
     * @return \App\Entity\VideoGame
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.J8C_T7p": it needs an instance of "App\\Entity\\VideoGame" but this type has been excluded in "config/services.yaml".');
    }
}
