<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VideoGame extends \App\Entity\VideoGame implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'advice' => [parent::class, 'advice', null],
        "\0".parent::class."\0".'averagePrice' => [parent::class, 'averagePrice', null],
        "\0".parent::class."\0".'averageUsersGrade' => [parent::class, 'averageUsersGrade', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'disponibility' => [parent::class, 'disponibility', null],
        "\0".parent::class."\0".'executionGrade' => [parent::class, 'executionGrade', null],
        "\0".parent::class."\0".'gameplayGrade' => [parent::class, 'gameplayGrade', null],
        "\0".parent::class."\0".'genders' => [parent::class, 'genders', null],
        "\0".parent::class."\0".'grade' => [parent::class, 'grade', null],
        "\0".parent::class."\0".'graphicsGrade' => [parent::class, 'graphicsGrade', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imgBox' => [parent::class, 'imgBox', null],
        "\0".parent::class."\0".'imgBoxFileName' => [parent::class, 'imgBoxFileName', null],
        "\0".parent::class."\0".'imgBoxSize' => [parent::class, 'imgBoxSize', null],
        "\0".parent::class."\0".'imgTheme' => [parent::class, 'imgTheme', null],
        "\0".parent::class."\0".'imgThemeFileName' => [parent::class, 'imgThemeFileName', null],
        "\0".parent::class."\0".'imgThemeSize' => [parent::class, 'imgThemeSize', null],
        "\0".parent::class."\0".'likes' => [parent::class, 'likes', null],
        "\0".parent::class."\0".'link' => [parent::class, 'link', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'platform' => [parent::class, 'platform', null],
        "\0".parent::class."\0".'releaseDate' => [parent::class, 'releaseDate', null],
        "\0".parent::class."\0".'storylineGrade' => [parent::class, 'storylineGrade', null],
        "\0".parent::class."\0".'titleReview' => [parent::class, 'titleReview', null],
        'advice' => [parent::class, 'advice', null],
        'averagePrice' => [parent::class, 'averagePrice', null],
        'averageUsersGrade' => [parent::class, 'averageUsersGrade', null],
        'comments' => [parent::class, 'comments', null],
        'description' => [parent::class, 'description', null],
        'disponibility' => [parent::class, 'disponibility', null],
        'executionGrade' => [parent::class, 'executionGrade', null],
        'gameplayGrade' => [parent::class, 'gameplayGrade', null],
        'genders' => [parent::class, 'genders', null],
        'grade' => [parent::class, 'grade', null],
        'graphicsGrade' => [parent::class, 'graphicsGrade', null],
        'id' => [parent::class, 'id', null],
        'imgBox' => [parent::class, 'imgBox', null],
        'imgBoxFileName' => [parent::class, 'imgBoxFileName', null],
        'imgBoxSize' => [parent::class, 'imgBoxSize', null],
        'imgTheme' => [parent::class, 'imgTheme', null],
        'imgThemeFileName' => [parent::class, 'imgThemeFileName', null],
        'imgThemeSize' => [parent::class, 'imgThemeSize', null],
        'likes' => [parent::class, 'likes', null],
        'link' => [parent::class, 'link', null],
        'name' => [parent::class, 'name', null],
        'platform' => [parent::class, 'platform', null],
        'releaseDate' => [parent::class, 'releaseDate', null],
        'storylineGrade' => [parent::class, 'storylineGrade', null],
        'titleReview' => [parent::class, 'titleReview', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
