<?php

namespace ContainerZGKUOjW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwG6nTGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TwG6nTG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TwG6nTG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cr' => ['privates', 'App\\Repository\\CommentsRepository', 'getCommentsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.TwG6nTG.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.TwG6nTG": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cr' => 'App\\Repository\\CommentsRepository',
            'em' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
