<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGKUOjW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGKUOjW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGKUOjW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGKUOjW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZGKUOjW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZGKUOjW',
    'container.build_id' => '0e38ee6b',
    'container.build_time' => 1715077273,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGKUOjW');
