<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLRCkO4x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLRCkO4x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLRCkO4x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLRCkO4x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLRCkO4x\App_KernelDevDebugContainer([
    'container.build_hash' => 'LRCkO4x',
    'container.build_id' => 'f683252f',
    'container.build_time' => 1713955748,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLRCkO4x');
